vscode:
  extensions:
    - asciidoctor.asciidoctor-vscode
    - mhutchie.git-graph
    - eamodio.gitlens
    - yandeu.five-server
tasks:
  - name: Setup environment
    init: >
      sudo apt-get -y install asciidoctor ruby-asciidoctor-pdf exiftool && 
      git config alias.s "status -sb" &&
      git config alias.staged "diff --cached" &&
      git config alias.co "checkout" &&
      git config alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit" &&
      git config alias.lga "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --all"
